classes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # clases #!Admin
    path('classes_list', views.classes_list, name='classes_list'),
    path('create_classes/', views.create_classes, name='create_classes'),
    path('edit_classes/<int:clase_id>/', views.edit_classes, name='edit_classes'),
    path('delete_classes/<int:clase_id>/', views.delete_classes, name='delete_classes'),
   #Clases #!Entrenador
   path('classes_entrenador/<int:user_id>/', views.classes_entrenador, name='classes_entrenador'),
    #Clases #!Miembros
    path('classes_miembros/', views.classes_miembros, name='classes_miembros'),
    path('classes_reserva/<int:user_id>/<int:clase_id>/', views.classes_reserva, name='classes_reserva'),
    path('reserve_list/', views.reserve_list, name='reserve_list'),
    path('reserve_delete/<int:reserva_id>', views.reserve_delete, name='reserve_delete'),
   
   
    # reserva
    path('reserve_list', views.reserve_list, name='reserve_list'),
    path('create_reserve/', views.create_reserve, name='create_reserve'),
    path('edit_reserve/<int:user_id>/', views.edit_reserve, name='edit_reserve'),
    path('delete_reserve/<int:user_id>/', views.delete_reserve, name='delete_reserve'),
    
]

gym_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('users/', include(('users.urls', 'users'), namespace='users')),  # Las URLs de la app users
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),  # Las URLs de la app classes
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),  # Las URLs de la app payments
    path('memberships/', include(('memberships.urls', 'memberships'), namespace='memberships')),  # Las URLs de la app memberships
    path('routines/', include(('routines.urls', 'routines'), namespace='routines')),  # Las URLs de la app routines
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

routines/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #! Admin
    path('routines_list', views.routines_list, name='routines_list'),
    path('create_routines/', views.create_routines, name='create_routines'),
    path('edit_routines/<int:rutina_id>/', views.edit_routines, name='edit_routines'),
    path('delete_routines/<int:rutina_id>/', views.delete_routines, name='delete_routines'),
    #! Entrenador
    path('routines_entreandor/<int:clase_id>/', views.routines_entrenador, name='routines_entrenador'),
    path('create_routines_entrenador/<int:clase_id>/', views.create_routines_entrenador, name='create_routines_entrenador'),
]

routines/models.py
from django.db import models
from django.conf import settings
from classes.models import Clase  # Importar la clase para asociarla

class Rutina(models.Model):
    clase = models.ForeignKey(Clase, on_delete=models.CASCADE)  # Relación con la clase
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    frecuencia = models.CharField(max_length=50)  # Ej. "3 veces por semana"
    duracion_minutos = models.PositiveIntegerField()  # Duración en minutos
    fecha_inicio = models.DateField()  # Fecha de inicio de la rutina
    fecha_fin = models.DateField(null=True, blank=True)  # Fecha de fin de la rutina, opcional
    is_active = models.BooleanField(default=True)  # Si la rutina está activa o no

    def __str__(self):
        return f"Rutina de {self.clase.nombre} - {self.nombre}"

routines/forms.py
from datetime import datetime
import pytz
from django.utils.timezone import make_aware
from django import forms
from .models import Rutina
from classes.models import Clase 

class RutinaForm(forms.ModelForm):
    class Meta:
        model = Rutina
        fields = ['clase', 'nombre', 'descripcion', 'frecuencia', 'duracion_minutos', 'fecha_inicio', 'fecha_fin']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Aplica clases CSS y placeholders a todos los campos
        self.fields['clase'].widget.attrs.update({'class': 'form-control'})
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de la Rutina'})
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Una Breve Descripción'})
        self.fields['frecuencia'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione la Fecuencia'})
        self.fields['duracion_minutos'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione la Duración'})
        self.fields['fecha_inicio'].widget = forms.DateInput(
            attrs={'class': 'form-control', 'placeholder': 'Fecha de Inicio', 'type': 'date'}
        )
        self.fields['fecha_fin'].widget = forms.DateInput(
            attrs={'class': 'form-control', 'placeholder': 'Fecha de Fin', 'type': 'date'}
        )       
        
        # Filtra los usuarios para que solo se muestren los entrenadores (is_staff=True)
        self.fields['clase'] = forms.ModelChoiceField(
            queryset=Clase.objects.all(),  # Solo los usuarios que son entrenadores
            empty_label="Seleccione una Clase",  # Etiqueta por defecto en el select
            widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Seleccione el Entrenador'}),
            to_field_name='id'  # Asegura que Django use el id para la validación.
        )
            
        # Campo para seleccionar la hora
        FRECUENCIA_CHOICES=[
            (1, '1 vez por semana'),
            (2, '2 veces port semana'),
            (3, '3 veces port semana'),
            (4, '4 veces por semana'),
            (5, '5 veces por semana'),
            (6, '6 veces por semana'),
    
        ]
        
        # Cambiar el campo de horario para que sea un select con opciones predefinidas
        self.fields['frecuencia'] = forms.ChoiceField(
            choices=FRECUENCIA_CHOICES,  # Utiliza las opciones de horario predefinidas
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        

      
        
        # Opcional: Elimina etiquetas (label) si las quieres vacías
        for field in self.fields.values():
            field.label = ''
         # Añadir etiquetas a los campos de fecha para que el usuario sepa cuál es cuál
        self.fields['fecha_inicio'].label = 'Fecha de Inicio'  # Etiqueta explícita para el campo de inicio
        self.fields['fecha_fin'].label = 'Fecha de Fin'  # Etiqueta explícita para el campo de fin
    
   
class RutinaEntrenadorForm(forms.ModelForm):
   

    class Meta:
        model = Rutina
        fields = ['clase', 'nombre', 'descripcion', 'frecuencia', 'duracion_minutos', 'fecha_inicio', 'fecha_fin']
    
    def __init__(self, *args, clase_id=None, **kwargs):
        super().__init__(*args, **kwargs)
        print("tenemos el id de clase", clase_id)
        
        # Aplica clases CSS y placeholders a todos los campos
        self.fields['clase'].widget.attrs.update({'class': 'form-control', 'disabled': 'true'})
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de la Rutina'})
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Una Breve Descripción'})
        self.fields['frecuencia'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione la Fecuencia'})
        self.fields['duracion_minutos'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione la Duración'})
        self.fields['fecha_inicio'].widget = forms.DateInput(
            attrs={'class': 'form-control', 'placeholder': 'Fecha de Inicio', 'type': 'date'}
        )
        self.fields['fecha_fin'].widget = forms.DateInput(
            attrs={'class': 'form-control', 'placeholder': 'Fecha de Fin', 'type': 'date'}
        )       
        
        # Filtra los usuarios para que solo se muestren los entrenadores (is_staff=True)
        self.fields['clase'] = forms.ModelChoiceField(
            queryset=Clase.objects.all(),  # Solo los usuarios que son entrenadores
            empty_label="Seleccione una Clase",  # Etiqueta por defecto en el select
            widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Seleccione el Entrenador'}),
            to_field_name='id'  # Asegura que Django use el id para la validación.
        )
            
        # Campo para seleccionar la hora
        FRECUENCIA_CHOICES=[
            (1, '1 vez por semana'),
            (2, '2 veces port semana'),
            (3, '3 veces port semana'),
            (4, '4 veces por semana'),
            (5, '5 veces por semana'),
            (6, '6 veces por semana'),
    
        ]
        
        # Cambiar el campo de horario para que sea un select con opciones predefinidas
        self.fields['frecuencia'] = forms.ChoiceField(
            choices=FRECUENCIA_CHOICES,  # Utiliza las opciones de horario predefinidas
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        
        # Opcional: Elimina etiquetas (label) si las quieres vacías
        for field in self.fields.values():
            field.label = ''
         # Añadir etiquetas a los campos de fecha para que el usuario sepa cuál es cuál
        self.fields['fecha_inicio'].label = 'Fecha de Inicio'  # Etiqueta explícita para el campo de inicio
        self.fields['fecha_fin'].label = 'Fecha de Fin'  # Etiqueta explícita para el campo de fin
        if clase_id:
            # Configura el campo clase
            self.fields['clase'].initial = clase_id  # Asigna el valor inicial del campo
            self.fields['clase'].disabled = True  # Desactívalo para que sea solo de lectura
        
    def clean(self):
        cleaned_data = super().clean()
        # Evitar cambios en el campo 'clase'
        if 'clase' in self.initial:
            cleaned_data['clase'] = self.initial['clase']
        return cleaned_data
    
   

routines/views.py
# routines/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Rutina
from classes.models import Clase

from .forms import RutinaForm, RutinaEntrenadorForm
from django.views.decorators.csrf import csrf_protect


# Vista para la lista de rutinas
@login_required
def routines_list(request):
    routines = Rutina.objects.all()  # Obtiene todos los usuarios
    return render(request, 'routines/routines_list.html', {'rutinas': routines, 'show_footer': True})

# Vista para la lista de rutinas del entrenador
@login_required
def routines_entrenador(request, clase_id ):
    routines = Rutina.objects.filter(clase=clase_id, is_active=True)  # Obtiene todos las rutinas de la clase
    clase_id = Clase.objects.get(id=clase_id)
    # print("clase_id",clase_id.id)
    return render(request, 'routines/routines_entrenador.html', {'rutinas': routines, 'clase_id':clase_id.id, 'user_id':clase_id.entrenador.id, 'show_footer': True})


# Vista para crear una nueva rutina
@login_required
@csrf_protect
def create_routines(request):
    if request.method == 'POST':
        form = RutinaForm(request.POST)
        if form.is_valid():
            routines = form.save(commit=False)
            routines.is_active = True  # Usuario activado por defecto
            routines.save()
            messages.success(request, "Rutina creada con éxito.")
            return redirect('routines:routines_list')
    else:
        form = RutinaForm()
    return render(request, 'routines/create_routines.html', {'form': form})


# Vista para crear una nueva rutina

@login_required
@csrf_protect
def create_routines_entrenador(request, clase_id):
    if request.method == 'POST':
        
        form = RutinaEntrenadorForm(request.POST, clase_id=clase_id)
        if form.is_valid():
            routines = form.save(commit=False)
            routines.is_active = True
            routines.save()
            messages.success(request, "Rutina creada con éxito.")
            return redirect('routines:routines_entrenador', clase_id=clase_id)
    else:
        form = RutinaEntrenadorForm(clase_id=clase_id)
    return render(request, 'routines/create_routines_entrenador.html', {'form': form, 'clase_id':clase_id})

# Vista para editar una rutina existente
@login_required
def edit_routines(request, rutina_id):
    rutina = get_object_or_404(Rutina, id=rutina_id)
    if request.method == 'POST':
        form = RutinaForm(request.POST, instance=rutina)
        if form.is_valid():
            form.save()
            messages.success(request, "Rutina editada con éxito.")
            return redirect('routines:routines_list')
    else:
        form = RutinaForm(instance=rutina)
    return render(request, 'routines/edit_routines.html', {'form': form})

# Vista para eliminar una rutina
@login_required
def delete_routines(request, rutina_id):
    rutina = get_object_or_404(Rutina, id=rutina_id)
    
    if request.method == 'POST':
        rutina.is_active = False  # Aplicamos Eliminacion logica
        rutina.save()
        messages.success(request, f"La Rutina {rutina.nombre} ha sido eliminado correctamente.")
        return redirect('routines:routines_list')  # Cambia al nombre correcto de tu lista de usuarios

    return render(request, 'routines/delete_routines.html', {'rutina': rutina})
   

routines/templates/routines/create_routines.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Crear Rutina{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/formRutinas.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Crear Rutina</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="botones">
            <button type="submit">Registrar</button>
            <button type="button" class="cancelar"><a href="{% url 'routines:routines_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>

{% endblock %}

routines/templates/routines/create_routines_entrenador.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Crear Rutina{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/formRutinas.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Crear Rutina</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="botones">
            <button type="submit">Registrar</button>
            <button type="button" class="cancelar"><a
                    href="{% url 'routines:routines_entrenador' clase_id %}">Cancelar</a></button>
        </div>
    </form>
</div>

{% endblock %}

routines/templates/routines/delete_routines.html
<!-- templates/users/delete_user.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} Eliminar Rutina | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/formRutinas.css' %}">
<!-- <link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}"> -->
{% endblock %}

{% block content %}
<div class="background"></div>

<div class="form-container">
    <h2>Eliminar Rutina</h2>
    <p>¿Estás seguro de que deseas eliminar la rutina <strong>{{ rutina.nombre }}</strong>? Esta acción no se puede
        deshacer.</p>

    <form method="POST">
        {% csrf_token %}
        <div class="botones">
            <button type="submit" class="eliminar">Eliminar</button>
            <button type="button" class="cancelar"><a href="{% url 'routines:routines_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>
{% endblock %}

routines/templates/routines/edit_routines.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Rutina{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/formRutinas.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Editar Rutina</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="botones">
            <button type="submit">Editar</button>
            <button type="button" class="cancelar"><a href="{% url 'routines:routines_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>

{% endblock %}

routines/templates/routines/routines_entrenador.html
<!-- templates/payments/clase_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} Rutinas | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/routines.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'routines:create_routines_entrenador' clase_id %}" class="boton_registro">Agregar Rutina</a>
<a href="{% url 'classes:classes_entrenador' user_id %}" class="boton_regresar">Regresar</a>
<h2> Rutinas de la Clase</h2>
<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Clase</th>
                <th>Rutina</th>
                <th>Descripcion</th>
                <th>Frecuencia</th>
                <th>Duracion (m)</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Fin</th>

            </tr>
        </thead>
        <tbody>
            {% for rutina in rutinas %}
            <tr>
                <td>{{ rutina.clase }}</td>
                <td>{{ rutina.nombre }}</td>
                <td>{{ rutina.descripcion }}</td>
                <td>{{ rutina.frecuencia }}</td>
                <td>{{ rutina.duracion_minutos }}</td>
                <td>{{ rutina.fecha_inicio }}</td>
                <td>
                    {% if rutina.fecha_fin %}
                    {{ rutina.fecha_fin }}
                    {% else %}
                    Sin definir
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

routines/templates/routines/routines_list.html
<!-- templates/payments/clase_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} Rutinas | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'routines/css/routines.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'routines:create_routines' %}" class="boton_registro">Agregar Nueva Rutina</a>
<h2>Lista de Rutinas</h2>

<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Clase</th>
                <th>Rutina</th>
                <th>Descripcion</th>
                <th>Frecuencia</th>
                <th>Duracion (m)</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Fin</th>
                <th>Estado</th>
                <th>Acción</th>

            </tr>
        </thead>
        <tbody>
            {% for rutina in rutinas %}
            <tr>
                <td>{{ rutina.clase }}</td>
                <td>{{ rutina.nombre }}</td>
                <td>{{ rutina.descripcion }}</td>
                <td>{{ rutina.frecuencia }}</td>
                <td>{{ rutina.duracion_minutos }}</td>
                <td>{{ rutina.fecha_inicio }}</td>
                <td>
                    {% if rutina.fecha_fin %}
                    {{ rutina.fecha_fin }}
                    {% else %}
                    Sin definir
                    {% endif %}
                </td>
                <td>
                    {% if rutina.is_active %}
                    Activo
                    {% else %}
                    Eliminado
                    {% endif %}
                </td>
                <td>
                    <div class="botones_accion">
                        {% if rutina.is_active %}
                        <a href="{% url 'routines:edit_routines' rutina.id %}" class="btn btn-warning btn-sm">
                            <img src="https://cdn-icons-png.flaticon.com/128/6324/6324826.png" alt=""></a>
                        <a href="{% url 'routines:delete_routines' rutina.id %}" class="btn btn-warning btn-sm">
                            <img src="https://cdn-icons-png.flaticon.com/128/2775/2775833.png" alt=""></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}