gym_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('users/', include(('users.urls', 'users'), namespace='users')),  # Las URLs de la app users
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),  # Las URLs de la app classes
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),  # Las URLs de la app payments
    path('memberships/', include(('memberships.urls', 'memberships'), namespace='memberships')),  # Las URLs de la app memberships
    path('routines/', include(('routines.urls', 'routines'), namespace='routines')),  # Las URLs de la app routines
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

users/urls.py
# users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user_list/', views.user_list, name='user_list'),  # Lista de usuarios
    path('register/', views.register, name='register'), # Registro de Usuario desde afuera
    path('user_register/', views.registerAdmin, name='user_register'), # Registro de Usuario por un admin
    path('login/', views.login_view, name='login'), # Inicio de Sesion
    path('logout/', views.logout_view, name='logout'), # Cierre de Sesion
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),  #Editar un usuario
    path('edit_perfile/<int:user_id>/', views.edit_perfile, name='edit_perfile'),  #Editar un usuario
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),  #Editar un usuario
        
]

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from memberships.models import Membership 


class User(AbstractUser):
    USER_TYPES = (
        (1, 'Administrador'),
        (2, 'Entrenador'),
        (3, 'Miembro'),
    )
   
    # Campo para definir el tipo de usuario
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPES, default=3)
    plan_membresia = models.ForeignKey(
        Membership,
        on_delete=models.SET_NULL,  # Si el plan es eliminado, el valor será NULL
        null=True,
        blank=True,
        related_name="users",  # Relación inversa desde Membership
    )
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    is_active = models.BooleanField(default=True)


    # Campos conflictivos con related_name personalizado
    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_groups",  # Evitar conflicto con el modelo auth.User
        blank=True,
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_permissions",  # Evitar conflicto con el modelo auth.User
        blank=True,
    )

    # Propiedad para facilitar la identificación del tipo de usuario
    @property
    def is_administrator(self):
        return self.user_type == 1

    @property
    def is_trainer(self):
        return self.user_type == 2

    @property
    def is_member(self):
        return self.user_type == 3

users/views.py
# users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import UserRegistrationForm, UserRegistrationAdminForm, UserEditForm, UserEditPerfileForm
from .models import User
from memberships.models import Membership
from payments.models import Pago
from django.views.decorators.csrf import csrf_protect


# Vista para el registro de usuarios
@csrf_protect
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True  # Usuario activado por defecto
            user.save()
            messages.success(request, "Cuenta creada con éxito. Ahora puedes iniciar sesión.")
            return redirect('users:login')
        else:
            print(form.errors)  # Imprime los errores del formulario
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})

# Vista para iniciar sesión
def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)  # Aquí se inicia sesión
                messages.success(request, 'Inicio de sesión exitoso.')
                return redirect('pages:index')  # Redirigir a la página de inicio después de iniciar sesión
            else:
                messages.error(request, "Tu cuenta está inactiva")
        else:
            messages.error(request, "Nombre de usuario o contraseña incorrectos")
    return render(request, 'users/login.html')

# Vista para cerrar sesión
@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Has cerrado sesión correctamente.')
    return redirect('users:login')

# Vista para registrar usuarios por parte del admin
def registerAdmin(request):
    if request.method == "POST":
        form = UserRegistrationAdminForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True  # Usuario activado por defecto
            user.save()
            membresia = get_object_or_404(Membership, id=user.plan_membresia)
            # Crear un registro de pago basado en el plan de membresía seleccionado
            Pago.objects.create(
                usuario=user,
                fecha_pago=None,
                monto=membresia.price,
                estado=3,
                plan=user.plan_membresia,  # Asigna el plan desde el usuario
            )            
            messages.success(request, "Cuenta creada con éxito. Ahora puedes iniciar sesión.")
            return redirect('users:login')
        else:
            print(form.errors)
    else:
        form = UserRegistrationAdminForm()

    return render(request, 'users/user_register.html', {'form': form, 'show_footer': True})


# Vista para editar un usuario (solo el admin puede acceder)
@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)  # Obtiene el usuario o 404 si no existe
    if request.method == "POST":
        form = UserEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            # Validamos si el usuario tiene un plan de membresía
            if user.plan_membresia:
                form.save()
                membresia = Membership.objects.filter(id=user.plan_membresia.id).first()
                # Crear un registro de pago basado en el plan de membresía seleccionado
                print("---------")
                print(membresia)
                if membresia:
                    Pago.objects.create(
                        usuario=user,
                        plan=membresia,
                        monto=membresia.price,  # Obtenemos el precio directamente
                        estado=1,  # Estado pendiente por defecto
                        metodo_pago=1,  # Método de pago predeterminado (Tarjeta)
                        descripcion=f'Pago por el plan {membresia.name}'
                    )
                messages.success(request, "Usuario actualizado con éxito.")
                return redirect('users:user_list')  # Redirige a la lista de usuarios después de editar
            else:
                messages.error(request, "Ingrese el tipo de membresia o plan")    
            
    else:
        form = UserEditForm(instance=user)
    return render(request, 'users/edit_user.html', {'form': form, 'user': user, 'show_footer': True})

# Vista para editar un usuario (solo el admin puede acceder)
@login_required
def edit_perfile(request, user_id):
    user = get_object_or_404(User, id=user_id)  # Obtiene el usuario o 404 si no existe
    if request.method == "POST":
        form = UserEditPerfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario actualizado con éxito.")
            return redirect('pages:index')  # Redirige a la lista de usuarios después de editar
    else:
        form = UserEditPerfileForm(instance=user)
    return render(request, 'users/edit_perfile.html', {'form': form, 'user': user, 'show_footer': True})

def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if request.method == 'POST':
        user.is_active = False  # Aplicamos Eliminacion logica
        user.save()
        messages.success(request, f"El usuario {user.username} ha sido eliminado correctamente.")
        return redirect('users:user_list')  # Cambia al nombre correcto de tu lista de usuarios

    return render(request, 'users/delete_user.html', {'user': user})


# Vista para ver la lista de usuarios
@login_required
def user_list(request):
    users = User.objects.all()  # Obtiene todos los usuarios
    return render(request, 'users/user_list.html', {'users': users, 'show_footer': True})

# Decorador de permisos para admins
def is_admin(user):
    return user.role == 'admin'

users/templates/users/delete_user.html
<!-- templates/users/delete_user.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} Eliminar Usuario | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<div class="background"></div>

<div class="form-container">
    <h2>Eliminar Usuario</h2>
    <p>¿Estás seguro de que deseas eliminar al usuario <strong>{{ user.username }}</strong>? Esta acción no se puede
        deshacer.</p>

    <form method="POST">
        {% csrf_token %}
        <div class="botones">
            <button type="submit" class="eliminar">Eliminar</button>
            <button type="button" class="cancelar"><a href="{% url 'users:user_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/edit_perfile.html
<!-- templates/users/edit_user.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} Editar | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Información Personal</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="botones">
            <button type="submit">Guardar</button>
            <button type="button" class="cancelar"><a href="{% url 'pages:index' %}">Cancelar</a></button>
        </div>
    </form>

</div>

{% endblock %}

users/templates/users/edit_user.html
<!-- templates/users/edit_user.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} Editar | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Modificar Usuario: {{ user.username }}</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="botones">
            <button type="submit">Editar Usuario</button>
            <button type="button" class="cancelar"><a href="{% url 'users:user_list' %}">Cancelar</a></button>
        </div>
    </form>

</div>

{% endblock %}

users/templates/users/login.html
<!-- users/templates/users/login.html -->
{% extends "base.html" %}
{% load static %}

{% block title %} Login | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del login -->
<div class="form-container">
    <h2>Iniciar Sesión</h2>
    <form method="POST">
        {% csrf_token %}

        <div>
            <label for="username">Nombre de usuario</label>
            <input type="text" name="username" id="username" class="form-control" required>
            {% if form.username.errors %}
            <div class="error">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="password">Contraseña</label>
            <input type="password" name="password" id="password" class="form-control" required>
            {% if form.password.errors %}
            <div class="error">{{ form.password.errors }}</div>
            {% endif %}
        </div>

        <button type="submit">Iniciar sesión</button>
    </form>
    <p>¿No tienes cuenta? <a href="{% url 'users:register' %}">Regístrate aquí</a></p>
</div>
{% endblock %}

users/templates/users/register.html
<!-- users/templates/users/register.html -->
{% extends "base.html" %}
{% load static %}

{% block title %} Registro | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Registrar Cuenta</h2>
    <form method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
    <p>¿Ya tienes cuenta? <a href="{% url 'users:login' %}">Iniciar sesión</a></p>

</div>
    
{% endblock %}

users/templates/users/user_list.html
<!-- templates/users/user_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} Usuarios | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/user_list.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'users:user_register' %}" class="boton_registro">Agregar Nuevo Usuario</a>
<h2>Lista de Usuarios</h2>

<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Email</th>
                <th>Rol</th>
                <th>Membresía</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.get_user_type_display }}</td>
                <td>{{ user.plan_membresia }}</td>
                <td>
                    {% if user.is_active %}
                    Activo
                    {% else %}
                    Eliminado
                    {% endif %}
                </td>
                <td>
                    <div class="botones_accion">
                        {% if user.is_active %}
                        <a href="{% url 'users:edit_user' user.id %}" class="btn btn-warning btn-sm">
                            <img src="https://cdn-icons-png.flaticon.com/128/6324/6324826.png" alt=""></a>
                        <a href="{% url 'users:delete_user' user.id %}" class="btn btn-warning btn-sm">
                            <img src="https://cdn-icons-png.flaticon.com/128/2775/2775833.png" alt=""></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

users/templates/users/user_register.html
<!-- users/templates/users/register.html -->
{% extends "base.html" %}
{% load static %}

{% block title %} Registro | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Registrar Cuenta</h2>
    <form method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
     
        <div class="botones">
            <button type="submit">Registrar Usuario</button>
            <button type="button"  class="cancelar"><a href="{% url 'users:user_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>
    
{% endblock %}