classes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # clases #!Admin
    path('classes_list', views.classes_list, name='classes_list'),
    path('create_classes/', views.create_classes, name='create_classes'),
    path('edit_classes/<int:clase_id>/', views.edit_classes, name='edit_classes'),
    path('delete_classes/<int:clase_id>/', views.delete_classes, name='delete_classes'),
   #Clases #!Entrenador
   path('classes_entrenador/<int:user_id>/', views.classes_entrenador, name='classes_entrenador'),
    #Clases #!Miembros
    path('classes_miembros/', views.classes_miembros, name='classes_miembros'),
    path('classes_reserva/<int:user_id>/<int:clase_id>/', views.classes_reserva, name='classes_reserva'),
    path('reserve_list/', views.reserve_list, name='reserve_list'),
    path('reserve_delete/<int:reserva_id>', views.reserve_delete, name='reserve_delete'),
   
   
    # reserva
    path('reserve_list', views.reserve_list, name='reserve_list'),
    path('create_reserve/', views.create_reserve, name='create_reserve'),
    path('edit_reserve/<int:user_id>/', views.edit_reserve, name='edit_reserve'),
    path('delete_reserve/<int:user_id>/', views.delete_reserve, name='delete_reserve'),
    
]

gym_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('users/', include(('users.urls', 'users'), namespace='users')),  # Las URLs de la app users
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),  # Las URLs de la app classes
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),  # Las URLs de la app payments
    path('memberships/', include(('memberships.urls', 'memberships'), namespace='memberships')),  # Las URLs de la app memberships
    path('routines/', include(('routines.urls', 'routines'), namespace='routines')),  # Las URLs de la app routines
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

payments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # pagos
    path('payments_list', views.payments_list, name='payments_list'),
    path('edit_payments/<int:pago_id>/', views.edit_payments, name='edit_payments'),
]

routines/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #! Admin
    path('routines_list', views.routines_list, name='routines_list'),
    path('create_routines/', views.create_routines, name='create_routines'),
    path('edit_routines/<int:rutina_id>/', views.edit_routines, name='edit_routines'),
    path('delete_routines/<int:rutina_id>/', views.delete_routines, name='delete_routines'),
    #! Entrenador
    path('routines_entreandor/<int:clase_id>/', views.routines_entrenador, name='routines_entrenador'),
    path('create_routines_entrenador/<int:clase_id>/', views.create_routines_entrenador, name='create_routines_entrenador'),
]

users/urls.py
# users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user_list/', views.user_list, name='user_list'),  # Lista de usuarios
    path('register/', views.register, name='register'), # Registro de Usuario desde afuera
    path('user_register/', views.registerAdmin, name='user_register'), # Registro de Usuario por un admin
    path('login/', views.login_view, name='login'), # Inicio de Sesion
    path('logout/', views.logout_view, name='logout'), # Cierre de Sesion
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),  #Editar un usuario
    path('edit_perfile/<int:user_id>/', views.edit_perfile, name='edit_perfile'),  #Editar un usuario
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),  #Editar un usuario
        
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block style %} {% endblock %}
</head>

<body>
    <nav>
        <div class="logo">GymX</div>
        <ul class="menu">
            <!-- Acceso público -->
            <li><a href="{% url 'pages:index' %}">Inicio</a></li>
            <li><a href="{% url 'pages:about' %}">Nosotros</a></li>
            <li><a href="{% url 'pages:services' %}">Servicios</a></li>
            <li><a href="{% url 'pages:contact' %}">Contacto</a></li>
            
            {% if user.is_authenticated %}
            <!-- Menú para usuarios logueados -->
                {% if user.user_type == 1 %}
                <!-- Menú del Administrador -->
                <li>
                    <a href="#gestion">Gestión</a>
                    <ul class="submenu">
                        <li><a href="{% url 'classes:classes_list' %}">Clases</a></li>
                        <li><a href="{% url 'routines:routines_list' %}">Rutinas</a></li>
                        <li><a href="{% url 'users:user_list' %}">Usuarios</a></li>
                        <li><a href="{% url 'memberships:memberships_list' %}">Membresía<s</a></li>
                        <li><a href="{% url 'payments:payments_list' %}">Pagos</a></li>
                    </ul>
                </li>
                {% elif user.user_type == 2 %}
                <!-- Menú del Entrenador -->
                <li>
                    <a href="#entrenamiento">Entrenamiento</a>
                    <ul class="submenu">
                        <li><a href="{% url 'classes:classes_entrenador' user.id %}">Mis Clases</a></li>
                    </ul>
                </li>
                {% elif user.user_type == 3 %}
                <!-- Menú del Miembro -->
                <li>
                    <a href="#mi_cuenta">Mi Cuenta</a>
                    <ul class="submenu">
                        <li><a href="{% url 'classes:reserve_list' %}">Mi Rutina</a></li>
                        <li><a href="{% url 'classes:classes_miembros' %}">Reservar Clases</a></li>
                        <li><a href="{% url 'memberships:memberships_user' user.id  %}">Mi Membresía</a></li>
                    </ul>
                </li>
                {% endif %}
            <!-- Opción de cerrar sesión -->
            <!-- <li><hr></li> -->
            <!-- <li><a href="{% url 'users:logout' %}">Cerrar sesión</a></li> -->
           
            <!-- Menú para usuarios no logueados -->
            
            <!-- <li><hr></li> -->
            <!-- <li><a href="{% url 'users:login' %}">Iniciar sesión</a></li> -->
                {% if show_footer %}
                <br>
                <!-- Menú del Perfil -->
                <li>
                    <a href="#mi_cuenta" class="img_perfil">
                        <img class="perfil" 
                        src="
                        {% if user.profile_picture.url != '' %}
                            {{ user.profile_picture.url }}
                        {% else %}
                            {% static 'img/logo.jpg' %}
                        {% endif %}" 
                        alt="Imgen de Perfil">
                        
                    </a>
                    <ul class="submenu">
                        <li><a href="{% url 'users:edit_perfile' user.id %}">Mi Perfil</a></li>
                        <li><a href="{% url 'users:logout' %}">Cerrar sesión</a></li>
                    </ul>
                </li>
                <br>
                
                {% endif %}


            {% endif %}

            {% if not user.is_authenticated and show_footer %}
            <br>
            <li><a href="{% url 'users:login' %}">Iniciar sesión</a></li>
            {% endif %}
        </ul>
        <div class="hamburger" onclick="toggleMenu()">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </nav>
    <!-- Mensaje de éxito o error -->
    {% if messages %}
        <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
        </div>
    {% endif %}

    <main class="main">
        
        {% block content %} {% endblock %}
    </main>

    {% if show_footer %}
    <!-- Footer -->
    <footer class="footer">
    <div class="footer-content">
        <div class="footer-logo">
            <img src="{% static 'img/logo.jpg'%}" alt="GymX Logo">
            <p>&copy; 2025 GymX. Todos los derechos reservados.</p>
        </div>
        <div class="footer-socials">
            <h4>Síguenos</h4>
            <div class="social-icons">
                <a href="#" class="social-icon" target="_blank"><img src="https://img.icons8.com/ios/50/ffffff/facebook.png" alt="Facebook"></a>
                <a href="#" class="social-icon" target="_blank"><img src="https://img.icons8.com/ios/50/ffffff/instagram-new.png" alt="Instagram"></a>
                <a href="#" class="social-icon" target="_blank"><img src="https://img.icons8.com/ios/50/ffffff/twitter.png" alt="Twitter"></a>
                <a href="#" class="social-icon" target="_blank"><img src="https://img.icons8.com/ios/50/ffffff/youtube-play.png" alt="YouTube"></a>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <p>Powered by <a href="#" target="_blank">Your Company</a></p>
    </div>
    </footer>

    {% endif %}

    {% block script %} {% endblock %}
    <script src="{% static 'js/menu.js' %}"></script>
</body>

</html>