classes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # clases #!Admin
    path('classes_list', views.classes_list, name='classes_list'),
    path('create_classes/', views.create_classes, name='create_classes'),
    path('edit_classes/<int:clase_id>/', views.edit_classes, name='edit_classes'),
    path('delete_classes/<int:clase_id>/', views.delete_classes, name='delete_classes'),
   #Clases #!Entrenador
   path('classes_entrenador/<int:user_id>/', views.classes_entrenador, name='classes_entrenador'),
    #Clases #!Miembros
    path('classes_miembros/', views.classes_miembros, name='classes_miembros'),
    path('classes_reserva/<int:user_id>/<int:clase_id>/', views.classes_reserva, name='classes_reserva'),
    path('reserve_list/', views.reserve_list, name='reserve_list'),
    path('reserve_delete/<int:reserva_id>', views.reserve_delete, name='reserve_delete'),
   
   
    # reserva
    path('reserve_list', views.reserve_list, name='reserve_list'),
    path('create_reserve/', views.create_reserve, name='create_reserve'),
    path('edit_reserve/<int:user_id>/', views.edit_reserve, name='edit_reserve'),
    path('delete_reserve/<int:user_id>/', views.delete_reserve, name='delete_reserve'),
    
]

gym_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('users/', include(('users.urls', 'users'), namespace='users')),  # Las URLs de la app users
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),  # Las URLs de la app classes
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),  # Las URLs de la app payments
    path('memberships/', include(('memberships.urls', 'memberships'), namespace='memberships')),  # Las URLs de la app memberships
    path('routines/', include(('routines.urls', 'routines'), namespace='routines')),  # Las URLs de la app routines
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

routines/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #! Admin
    path('routines_list', views.routines_list, name='routines_list'),
    path('create_routines/', views.create_routines, name='create_routines'),
    path('edit_routines/<int:rutina_id>/', views.edit_routines, name='edit_routines'),
    path('delete_routines/<int:rutina_id>/', views.delete_routines, name='delete_routines'),
    #! Entrenador
    path('routines_entreandor/<int:clase_id>/', views.routines_entrenador, name='routines_entrenador'),
    path('create_routines_entrenador/<int:clase_id>/', views.create_routines_entrenador, name='create_routines_entrenador'),
]

classes/models.py
from django.db import models
from datetime import date
from django.conf import settings  # Importar settings para AUTH_USER_MODEL

class Clase(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    entrenador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha = models.DateField(default=date.today)
    hora = models.CharField(max_length=5)
    cupo_maximo = models.PositiveIntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class Reserva(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    clase = models.ForeignKey(Clase, on_delete=models.CASCADE, related_name="reservas")
    fecha_reserva = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"Reserva de {self.usuario.username} en {self.clase.nombre}"

classes/forms.py
from datetime import datetime
import pytz
from django.utils.timezone import make_aware
from django import forms
from .models import Clase, Reserva
from users.models import User 

class ClaseForm(forms.ModelForm):
    # Campo para seleccionar la fecha
    fecha = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',  # Selector de fecha nativo del navegador
                'placeholder': 'Seleccione la fecha'
            }
        )
    )
    class Meta:
        model = Clase
        fields = ['nombre', 'descripcion', 'entrenador', 'fecha', 'hora', 'cupo_maximo']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Aplica clases CSS y placeholders a todos los campos
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de la Clase'})
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Descripcion de la Clase'})
        self.fields['entrenador'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione el Entrenador'})
        self.fields['hora'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Seleccione un Horario'})
        
        self.fields['cupo_maximo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Cupo Máximo'})
        
        # Filtra los usuarios para que solo se muestren los entrenadores (is_staff=True)
        self.fields['entrenador'] = forms.ModelChoiceField(
            queryset=User.objects.filter(user_type=2),  # Solo los usuarios que son entrenadores
            empty_label="Seleccione un Entrenador",  # Etiqueta por defecto en el select
            widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Seleccione el Entrenador'}),
            to_field_name='id'  # Asegura que Django use el id para la validación.
        )
            
        # Campo para seleccionar la hora
        HORARIO_CHOICES=[
            ('09:00', '09:00 AM'),
            ('10:00', '10:00 AM'),
            ('11:00', '11:00 AM'),
            ('12:00', '12:00 PM'),
            ('13:00', '01:00 PM'),
            ('14:00', '02:00 PM'),
            ('15:00', '03:00 PM'),
            ('16:00', '04:00 PM'),
            ('17:00', '05:00 PM'),
        ]
        
        # Cambiar el campo de horario para que sea un select con opciones predefinidas
        self.fields['hora'] = forms.ChoiceField(
            choices=HORARIO_CHOICES,  # Utiliza las opciones de horario predefinidas
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        

      
        # Asegurarse de que 'cupo_maximo' sea un campo entero
        self.fields['cupo_maximo'] = forms.IntegerField(
            widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cupo Máximo'}),
            min_value=1,  # Por ejemplo, el cupo máximo no puede ser menor que 1
        )
        
        
        # Opcional: Elimina etiquetas (label) si las quieres vacías
        for field in self.fields.values():
            field.label = ''
    
   
class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['clase']

classes/views.py
# classes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Clase, Reserva
from users.models import User
from .forms import ClaseForm, ReservaForm
from django.views.decorators.csrf import csrf_protect


# Vista para la lista de clases #!Admin
@login_required
def classes_list(request):
    classes = Clase.objects.all()  # Obtiene todos los usuarios
    return render(request, 'classes/classes_list.html', {'clases': classes, 'show_footer': True})

# Vista para la lista de clases #!Entrenador
@login_required
def classes_entrenador(request, user_id):
    classes = Clase.objects.filter(entrenador=user_id, is_active=True)  # Obtiene todos los usuarios
    
    return render(request, 'classes/classes_entrenador.html', {'clases': classes, 'show_footer': True})

# Vista para la lista de clases #!Miembros
@login_required
def classes_miembros(request):
    from django.db.models import Q
    user = request.user.id
    classes = Clase.objects.filter(is_active=True).exclude(
        id__in=Reserva.objects.filter(
            Q(usuario=user) & Q(is_active=True)  # Excluir reservas activas
        ).values('clase_id'))
    return render(request, 'classes/classes_miembros.html', {'clases': classes, 'show_footer': True})


# Vista para crear una nueva clase
@login_required
@csrf_protect
def create_classes(request):
    if request.method == 'POST':
        form = ClaseForm(request.POST)
        print("Esto es formulario")
        print(form)
        if form.is_valid():
            
            form.save()
            messages.success(request, "Clase creada con éxito.")
            return redirect('classes:classes_list')
    else:
        form = ClaseForm()
    return render(request, 'classes/create_classes.html', {'form': form})

# Vista para editar una clase existente
@login_required
def edit_classes(request, clase_id):
    clase = get_object_or_404(Clase, id=clase_id)
    if request.method == 'POST':
        form = ClaseForm(request.POST, instance=clase)
        if form.is_valid():
            form.save()
            messages.success(request, "Clase editada con éxito.")
            return redirect('classes:classes_list')
    else:
        form = ClaseForm(instance=clase)
    return render(request, 'classes/edit_classes.html', {'form': form})

# Vista para eliminar una clase
@login_required
def delete_classes(request, clase_id):
    clase = get_object_or_404(Clase, id=clase_id)
    
    if request.method == 'POST':
        clase.is_active = False  # Aplicamos Eliminacion logica
        clase.save()
        messages.success(request, f"La clase {clase.nombre} ha sido eliminado correctamente.")
        return redirect('classes:classes_list')  # Cambia al nombre correcto de tu lista de usuarios
    return render(request, 'classes/delete_classes.html', {'clase': clase})
    

# Vista para la lista de reservas
@login_required
def classes_reserva(request, user_id, clase_id):
    
    user = request.user
    clase = get_object_or_404(Clase, id=clase_id)
    # Verificar si la reserva ya existe para este usuario y clase
    if not Reserva.objects.filter(usuario=user, clase=clase_id, is_active=True).exists():
        reserva = Reserva(usuario=user, clase=clase)
        reserva.save()  # Guardar la nueva reserva
        messages.success(request, f"Reserva creada para el usuario {user.username} para la clase {clase.nombre}")
    else:
        messages.success(request, "Ya existe una reserva para este usuario y clase.")
    return redirect('classes:classes_miembros')



# Vista para la lista de reservas #!Miembros
@login_required 
def reserve_list(request):
    user = request.user.id
    reservas = Reserva.objects.filter(usuario=user, is_active=True)

    return render(request, 'classes/reserva_list.html', {'reservas': reservas, 'show_footer': True})

# Vista para la lista de reservas #!Miembros
@login_required 
def reserve_delete(request, reserva_id):
    reserva = get_object_or_404(Reserva, id=reserva_id)
    
    reserva.is_active = False  # Aplicamos Eliminacion logica
    reserva.save()
    messages.success(request, f"La reserva ha sido eliminado correctamente.")
    return redirect('classes:reserve_list')  # Cambia al nombre correcto de tu lista de usuarios

    
    
    
    # user = request.user.id
    # reservas = Reserva.objects.filter(usuario=user)

    # return render(request, 'classes/reserva_list.html', {'reservas': reservas, 'show_footer': True})





# Vista para crear una nueva reserva
@login_required
def create_reserve(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            reserva = form.save(commit=False)
            reserva.usuario = request.user  # Asigna el usuario al crear la reserva
            reserva.save()
            messages.success(request, "Reserva creada con éxito.")
            return redirect('classes:reserve_list')
    else:
        form = ReservaForm()
    return render(request, 'classes/reserva_register.html', {'form': form})

# Vista para editar una reserva existente
@login_required
def edit_reserve(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    if request.method == 'POST':
        form = ReservaForm(request.POST, instance=reserva)
        if form.is_valid():
            form.save()
            messages.success(request, "Reserva editada con éxito.")
            return redirect('classes:reserve_list')
    else:
        form = ReservaForm(instance=reserva)
    return render(request, 'classes/reserva_register.html', {'form': form})

# Vista para eliminar una reserva
@login_required
def delete_reserve(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    reserva.delete()
    messages.success(request, "Reserva eliminada con éxito.")
    return redirect('classes:reserve_list')

classes/templates/classes/classes_entrenador.html
<!-- templates/classes/clase_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} Mis Clases | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/clase.css' %}">
{% endblock %}

{% block content %}
<h2>Mis Clases</h2>

<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Entrenador</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Cupo Máximo</th>
                <th>Acción</th>

            </tr>
        </thead>
        <tbody>
            {% for clase in clases %}
            <tr>
                <td>{{ clase.nombre }}</td>
                <td>{{ clase.descripcion }}</td>
                <td>{{ clase.entrenador }}</td>
                <td>{{ clase.fecha }}</td>
                <td>{{ clase.hora }}</td>
                <td>{{ clase.cupo_maximo }}</td>
                <td>
                    <div class="botones_accion">
                        {% if clase.is_active %}
                        <a href="{% url 'routines:routines_entrenador' clase.id %}" class="btn btn-warning btn-sm">
                            <img src="{% static 'img/ver.png' %}" alt="Eliminar"></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

classes/templates/classes/classes_list.html
<!-- templates/classes/clase_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} Clases | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/clase.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'classes:create_classes' %}" class="boton_registro">Agregar Nueva Clase</a>
<h2>Lista de Clases</h2>

<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Entrenador</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Cupo Máximo</th>
                <th>Estado</th>
                <th>Acción</th>

            </tr>
        </thead>
        <tbody>
            {% for clase in clases %}
            <tr>
                <td>{{ clase.nombre }}</td>
                <td>{{ clase.descripcion }}</td>
                <td>{{ clase.entrenador }}</td>
                <td>{{ clase.fecha }}</td>
                <td>{{ clase.hora }}</td>
                <td>{{ clase.cupo_maximo }}</td>
                <td>
                    {% if clase.is_active %}
                    Activo
                    {% else %}
                    Eliminado
                    {% endif %}
                </td>
                <td>
                    <div class="botones_accion">
                        {% if clase.is_active %}
                        <a href="{% url 'classes:edit_classes' clase.id %}" class="btn btn-warning btn-sm">
                            <img src="{% static 'img/editar.png' %}" alt="Editar"></a>
                        <a href="{% url 'classes:delete_classes' clase.id %}" class="btn btn-warning btn-sm">
                            <img src="{% static 'img/eliminar.png' %}" alt="Eliminar"></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

classes/templates/classes/classes_miembros.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Clases | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/clase.css' %}">
{% endblock %}

{% block content %}
<h2>Clases Disponibles</h2>

<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Entrenador</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Cupo Máximo</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for clase in clases %}
            <tr>
                <td>{{ clase.nombre }}</td>
                <td>{{ clase.descripcion }}</td>
                <td>{{ clase.entrenador }}</td>
                <td>{{ clase.fecha }}</td>
                <td>{{ clase.hora }}</td>
                <td>{{ clase.cupo_maximo }}</td>
                <td>
                    <div class="botones_accion">
                        {% if clase.is_active %}
                        <a href="{% url 'classes:classes_reserva' user.id clase.id %}" class="btn btn-warning btn-sm">
                            <img src="{% static 'img/editar.png' %}" alt="Reserva"></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

classes/templates/classes/create_classes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Crear Clase{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/formClases.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Crear Clase</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="botones">
            <button type="submit">Registrar</button>
            <button type="button" class="cancelar"><a href="{% url 'classes:classes_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>

{% endblock %}

classes/templates/classes/delete_classes.html
<!-- templates/users/delete_user.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} Eliminar Clase | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/autenticacion.css' %}">
{% endblock %}

{% block content %}
<div class="background"></div>

<div class="form-container">
    <h2>Eliminar Clase</h2>
    <p>¿Estás seguro de que deseas eliminar la clase <strong>{{ clase.nombre }}</strong>? Esta acción no se puede
        deshacer.</p>

    <form method="POST">
        {% csrf_token %}
        <div class="botones">
            <button type="submit" class="eliminar">Eliminar</button>
            <button type="button" class="cancelar"><a href="{% url 'classes:classes_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>
{% endblock %}

classes/templates/classes/edit_classes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Clase{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/formClases.css' %}">
{% endblock %}

{% block content %}
<!-- Fondo borroso -->
<div class="background"></div>

<!-- Contenedor del Registro -->
<div class="form-container">
    <h2>Editar Clase</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="botones">
            <button type="submit">Editar</button>
            <button type="button" class="cancelar"><a href="{% url 'classes:classes_list' %}">Cancelar</a></button>
        </div>
    </form>
</div>

{% endblock %}

classes/templates/classes/reserva_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mis Reserrvas | GymX {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'classes/css/clase.css' %}">
{% endblock %}

{% block content %}
<h2>Mis Reservas</h2>
<div class="table-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Clase</th>
                <th>Fecha de Reserva</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            {% for reserva in reservas %}
            <tr>
                <td>{{ reserva.usuario }}</td>
                <td>{{ reserva.clase }}</td>
                <td>{{ reserva.fecha_reserva }}</td>
                <td>
                    <div class="botones_accion">
                        {% if reserva.is_active %}
                        <a href="{% url 'classes:reserve_delete' reserva.id %}" class="btn btn-warning btn-sm">
                            <img src="{% static 'img/eliminar.png' %}" alt="Eliminar"></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}